// Code generated by Machine, Do not edit

package main

import (
	"log"
	"testing"
)

func TestProcessAnimal0(t *testing.T) {
	valuesMap := map[string]interface{}{
		"Legs":   3,
		"Name":   "zJLyD",
		"Roar":   false,
		"Voice":  "QTnhfSFLmQ",
		"Weight": 62.17153096767728,
	}
	var cat Animal
	if err := processAnimal(cat, valuesMap); err != nil {
		log.Println(err)
	}
}
func TestProcessAnimal1(t *testing.T) {
	valuesMap := map[string]interface{}{
		"Legs":   1,
		"Name":   "GpkHP",
		"Roar":   false,
		"Voice":  "rrUSJzRZsO",
		"Weight": 15.77042060757389,
	}
	var cat Animal
	if err := processAnimal(cat, valuesMap); err != nil {
		log.Println(err)
	}
}
func TestProcessAnimal2(t *testing.T) {
	valuesMap := map[string]interface{}{
		"Legs":   3,
		"Name":   "CAYyo",
		"Roar":   false,
		"Voice":  "rSlTxhpdcp",
		"Weight": 19.728181751851213,
	}
	var cat Animal
	if err := processAnimal(cat, valuesMap); err != nil {
		log.Println(err)
	}
}
func TestProcessAnimal3(t *testing.T) {
	valuesMap := map[string]interface{}{
		"Legs":   0,
		"Name":   "kGdZT",
		"Roar":   false,
		"Voice":  "RxtHAXbBUx",
		"Weight": 95.4065849359672,
	}
	var cat Animal
	if err := processAnimal(cat, valuesMap); err != nil {
		log.Println(err)
	}
}
func TestProcessAnimal4(t *testing.T) {
	valuesMap := map[string]interface{}{
		"Legs":   2,
		"Name":   "aKFPO",
		"Roar":   false,
		"Voice":  "BeHyAUgvMe",
		"Weight": 15.063844447611864,
	}
	var cat Animal
	if err := processAnimal(cat, valuesMap); err != nil {
		log.Println(err)
	}
}
